import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
     src: "./fonts/Geist-Regular.woff2",
  variable: "--font-geist-sans",
  weight:"400"
});

const geistMono = localFont({
   src: "./fonts/GeistMono-Regular.woff2",
  variable: "--font-geist-mono",
  weight:"400" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
