import type { Metadata } from "next";
import MyContext from "./components/Context";
import { Geist, Geist_Mono } from "next/font/google";
import Unauthorize from "./components/Unauthorize";
import "./globals.css";
import SessionProviderWrapper from "../app/components/providers";
import { getAuthSession } from "@/utils/getSession";
import Header from "./components/Header";
import Footer from "./components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper session={session}>
          <MyContext>
            <Header />
            <Unauthorize>
              {children}
            </Unauthorize>
            <Footer />
          </MyContext>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
